                       <div class="art-layout-cell art-content">
							<div class="art-post">
                                <div class="art-post-tl"></div>
                                <div class="art-post-tr"></div>
                                <div class="art-post-bl"></div>
                                <div class="art-post-br"></div>
                                <div class="art-post-tc"></div>
                                <div class="art-post-bc"></div>
                                <div class="art-post-cl"></div>
                                <div class="art-post-cr"></div>
                                <div class="art-post-cc"></div>
                                <div class="art-post-body">
	                            	<div class="art-post-inner art-article">
	                                            <h2 class="art-postheader">
	                                                Je kunt contact opnemen via
	                                            </h2>
	                                            <div class="art-postcontent">
	                                                <!-- article-content -->
	                                                
	                                                <img alt="telefoon" src="/images/iconphone.gif" />+31 (0) 6 52 31 31 45<br />
	                                                <hr />
													<img alt="email" src="/images/iconemail.gif" /> <a href="mailto:info@jaspervanherpt.com">info@jaspervanherpt.com</a><br />
													<hr />
													<img alt="website" src="/images/iconglobe.gif" /><a href="http://www.jaspervanherpt.com">www.jaspervanherpt.com</a><br />
	                                                	                                                    
	                                                <!-- /article-content -->
	                                            </div>
	                                            <div class="cleared"></div>
	                            	</div>
	                            	<div class="cleared"></div>
                                </div>
                            </div>
                            
                        </div>