<?php $this->jQuery()->enable(); ?>                            
                            <div class="art-post">
                                <div class="art-post-tl"></div>
                                <div class="art-post-tr"></div>
                                <div class="art-post-bl"></div>
                                <div class="art-post-br"></div>
                                <div class="art-post-tc"></div>
                                <div class="art-post-bc"></div>
                                <div class="art-post-cl"></div>
                                <div class="art-post-cr"></div>
                                <div class="art-post-cc"></div>
                                <div class="art-post-body">
                            <div class="art-post-inner art-article">
                                            <h2 class="art-postheader">
                                                <?php echo $this->frontArticle->getTitle(); ?>
                                            </h2>
                                            <div class="art-postcontent">
                                                <!-- article-content -->
                                                
                                                
                                                <?php echo $this->frontArticle->getContent(); ?>
                                                    
                                                <!-- /article-content -->
                                            </div>
                                            <div class="cleared"></div>
                            </div>                            
                            		<div class="cleared"></div>
                                </div>
                                
                            </div>
                          
                            	<div id="accordion">
		                            <h3><a href="#"><b>Webhosting door Hostgator</b></a></h3>
		                            <div style="display: block; height:300px; ">
		                            <p>
		                            Een <a href="http://www.basdebie.com" target="_blank">oud collega</a> wees me eens op onderstaande partij en ik deel zijn enthousiasme.<br />
		                            Je kunt hier voor een zeer schappelijk bedrag een webhosting pakket krijgen waarmee je meerdere domeinen probleemloos
		                            en beheert. Zelf heb ik momenteel maar 7 domeinen lopen maar tientallen is ook geen enkel probleem, voor een schamele
		                            $100 (dollar!) per jaar heb je onbeperkte bandbreedte, kun je een onbeperkt domeinnamen koppelen en heb je onbeperkte
		                            schijfruimte op de server.
		                            </p>   
		                            <a href="http://secure.hostgator.com/~affiliat/cgi-bin/affiliates/clickthru.cgi?id=jaspervanherpt-"><img src="http://tracking.hostgator.com/img/Green/468x60.gif" border=0 /></a>
		                            </div>
		                            <h3><a href="#">Webbuilding door Dionne Willemse</a></h3>
		                            <div>
		                            <p>
		                            Voor mooi website design op basis van Joomla kijk op
		                            <a href="http://www.dionnewillemse.com">www.dionnewillemse.com</a> <br />
		                            <br />
		                            Kunstzinnig, vlot & modern! <br />
		                            <br />
		                            </p>
		                            </div>
		                            <br />
	                            </div>
                            